name: MacOS_arm64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: build

    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.13"
        architecture: "arm64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: |
        rm -rf build
        rm -rf dist
        rm -rf app.spec
        pyinstaller -F --clean --target-arch arm64 ./app.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacOS_arm64
        path: ./dist/app
