# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build MacOS 12 Application Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        rm -rf build
        rm -rf dist
        rm -rf app.spec
        # python setup.py py2app
        pyinstaller -F --clean ./app.py
    - name: Create Zip Package
      run: |
        zip -r ./dist/app.zip ./dist/app
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app.zip
        path: ./dist/app.zip
